### ISSUE TITLE
Constant already initialized warning

### ISSUE THREAD

**Issue by petems** [puppetlabs/beaker-rspec#54]
```
/Users/petersouter/.bundler/ruby/2.0.0/beaker-rspec-bbf806a4fc12/lib/beaker-rspec/helpers/serverspec.rb:12: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/Library/Ruby/Gems/2.0.0/gems/specinfra-2.11.5/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
```

**Comment by nibalizer** [comment]
I get this too:

http://planck.nibalizer.com/buildlogs/puppetlabs+puppetlabs-apache+978+1424904115+FAIL

**Comment by electrical** [comment]
Hi guys,

This is because of serverspec/specinfra 2.x
They made certain changes that conflicted with beaker.
We had to override certain stuff to make it work.

This work was done with https://github.com/puppetlabs/beaker-rspec/pull/51

Reasoning for it is inline: https://github.com/puppetlabs/beaker-rspec/blob/master/lib/beaker-rspec/helpers/serverspec.rb#L38-L39

**Comment by anodelman** [comment]
Resolved (or, at least, explained) in last comment.
