### ISSUE TITLE
How to confine test to role

### ISSUE THREAD

**Issue by jimcroft** [puppetlabs/beaker-rspec#65]
I'm working on adding tests for an existing module that sets up a cluster. There are cluster roles such as master, peer, searchhead and forwarder.

I've got my nodeset configured to bring up the appropriate vagrant VMs. What I need to do is run certain test cases on all node and others on hosts with a specific role.

I can see confine and confine_block block methods in the Beaker DSL but have no idea how to use them in beaker-rspec. I've tried the following without success:

```
confine_block :to, role: 'searchhead' do
    describe service('myservice') do
        it { should be_running }
    end
end
```

The other thing I could do split out tests for individual roles into different spec files. But even then I'm not sure how to run specific spec files against specific roles without some nasty hackery.

Any suggestions appreciated.

**Comment by bodgit** [comment]
I came across while looking to do the same thing. If I use the following:

```ruby
confine_block :to, :roles => 'nonexistentrole' do
  ...
end
```

then I can trigger the following warning:

```
Warning: No suitable hosts with: {:roles=>"nonexistentrole"}

No suitable hosts found
```

Whereas if I use `role` with any value I can't trigger any warning. So it suggests using `roles` rather than `role` is the right condition perhaps?
However either with that or using a role that *does* exist in the nodeset, I always get the following error:

```
.../gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:635:in `method_missing': undefined method `hosts=' for RSpec::ExampleGroups::OpenldapServer::Test:Class (NoMethodError)
	from .../gems/beaker-2.10.0/lib/beaker/dsl/structure.rb:200:in `ensure in confine_block'
	from .../gems/beaker-2.10.0/lib/beaker/dsl/structure.rb:200:in `confine_block'
...
```

My test case is for testing an LDAP replication setup using a module I've written; so I want to put the same class on all nodes with slightly different parameters on the producer/master vs the consumers/slaves, import sample content on the master and then check that all nodes agree on the content to confirm the module set up the replication correctly.

**Comment by anodelman** [comment]
confine and confine_block are not currently supported in beaker-rspec.

I'm moving bugs to our Jira tracker.

Follow up here: https://tickets.puppetlabs.com/browse/BKR-289
